### PR TITLE
[PROTEUS-64] Lasso integration in Proteus job

### PR DESCRIPTION
**Pull request by jdematias**
Lasso algorithm integration in Proteus job

### CODE REVIEW

**Comment by VenturaDelMonte** [comment]
Does the last commit depend on this SOLMA PR [1]?

[1] https://github.com/proteus-h2020/proteus-solma/pull/38

**Comment by jdematias** [comment]
Yes, it is necessary

**Review by VenturaDelMonte — CHANGES_REQUESTED** [review]
Hi Javier, sorry for my late answer. I checked your code and tested with a debugger. The problem deals with the iterationWaitTime. In your code it is set to 10ms, which means that if the PS does not receive anything within 10ms, then it gets shut down. Increasing the wait time to 20000ms solves the issue ;)

**Comment by jdematias** [comment]
Thanks Ventura!! I increased wait time and I think now PR is ready to merge

**Comment by VenturaDelMonte** [comment]
do you know why travis is still failing? Btw, i also think the PR is ready.

**Comment by jdematias** [comment]
There are not .travis.yml file :)

**Comment by VenturaDelMonte** [comment]
Ah I see, it makes sense. Merging now..

**Review by VenturaDelMonte — APPROVED** [review]

**Pull request merged**
